export const FroalaActivationKey = import.meta.FROALA_ACTIVATION_KEY

export const FroalaToolbarButtons = [
	"alignCenter",
	"alignJustify",
	"alignLeft",
	"alignRight",
	// "backgroundColor",
	"textColor",
	"bold",
	"italic",
	"strikeThrough",
	"underline",
	"clearFormatting",
	// "fontFamily",
	"fontSize",
	"formatOL",
	// "formatOLSimple",
	"formatUL",
	// "fullscreen",
	// "getPDF",
	// "help",
	"html",
	"indent",
	"outdent",
	// "inlineClass",
	// "inlineStyle",
	// "insertFile",
	"insertHR",
	// "insertImage",
	"insertLink",
	// "insertTable",
	// "insertVideo",
	// "lineHeight",
	// "paragraphFormat",
	// "paragraphStyle",
	// "print",
	// "quote",
	"undo",
	"redo",
	// "selectAll",
	"specialCharacters",
	// "spellChecker",
	// "subscript",
	// "superscript",
]

// export const FroalaToolbarButtonsMD = [
// 	"alignCenter",
// 	"alignJustify",
// 	"alignLeft",
// 	"alignRight",
// 	"backgroundColor",
// 	"bold",
// 	"clearFormatting",
// 	"fontFamily",
// 	"fontSize",
// 	"fullscreen",
// 	"getPDF",
// 	"help",
// 	"html",
// 	"indent",
// 	"inlineClass",
// 	"inlineStyle",
// 	"insertFile",
// 	"insertHR",
// 	"insertImage",
// 	"insertLink",
// 	"italic",
// 	"lineHeight",
// 	"outdent",
// 	"paragraphFormat",
// 	"paragraphStyle",
// 	"print",
// 	"quote",
// 	"redo",
// 	"selectAll",
// 	"strikeThrough",
// 	"textColor",
// 	"underline",
// 	"undo"
// ]
//
// export const FroalaToolbarButtonsSM = [
// 	"alignCenter",
// 	"alignJustify",
// 	"alignLeft",
// 	"alignRight",
// 	"backgroundColor",
// 	"bold",
// 	"clearFormatting",
// 	"fontFamily",
// 	"fontSize",
// 	"fullscreen",
// 	"help",
// 	"html",
// 	"indent",
// 	"italic",
// 	"lineHeight",
// 	"outdent",
// 	"paragraphFormat",
// 	"paragraphStyle",
// 	"print",
// 	"quote",
// 	"redo",
// 	"selectAll",
// 	"strikeThrough",
// 	"textColor",
// 	"underline",
// 	"undo"
// ]
//
// export const FroalaToolbarButtonsXS = [
// 	"alignCenter",
// 	"alignJustify",
// 	"alignLeft",
// 	"alignRight",
// 	"backgroundColor",
// 	"bold",
// 	"clearFormatting",
// 	"fontFamily",
// 	"fontSize",
// 	"fullscreen",
// 	"help",
// 	"html",
// 	"indent",
// 	"italic",
// 	"lineHeight",
// 	"outdent",
// 	"paragraphFormat",
// 	"paragraphStyle",
// 	"print",
// 	"quote",
// 	"redo",
// 	"selectAll",
// 	"strikeThrough",
// 	"textColor",
// 	"underline",
// 	"undo"
// ]

// {
// 	"moreText": {
// 	"buttons": ["bold", "italic", "underline", "strikeThrough", "subscript", "superscript", "fontFamily", "fontSize", "textColor", "backgroundColor", "inlineClass", "inlineStyle", "clearFormatting"]
// },
// 	"moreParagraph": {
// 	"buttons": ["alignLeft", "alignCenter", "formatOLSimple", "alignRight", "alignJustify", "formatOL", "formatUL", "paragraphFormat", "paragraphStyle", "lineHeight", "outdent", "indent", "quote"]
// },
// 	"moreRich": {
// 	"buttons": ["insertLink", "insertImage", "insertVideo", "insertTable", "emoticons", "fontAwesome", "specialCharacters", "embedly", "insertFile", "insertHR"]
// },
// 	"moreMisc": {
// 	"buttons": ["undo", "redo", "fullscreen", "html", "print", "getPDF", "spellChecker", "selectAll", "help"],
// 		"align": "right",
// 		"buttonsVisible": 3
// }
// }
